### PR TITLE
inst_server: Added error handling for commit fails

### PR DESCRIPTION
**Pull request by mattclarke**
### Description of work

https://github.com/ISISComputingGroup/IBEX/issues/1944

### To test

If there is a git lock present then the devices screen code throws an unhandled error, so doesn't assign data to the PVs.

You can recreate by creating a lock file in the appropriate directory, for example: `C:\Instrument\Settings\config\NDXDEMO\.git\logs\refs\heads\NDXDEMO.lock`

The file is empty.

Before the change if the lock exists then `caget -S -t IN:DEMO:CS:BLOCKSERVER:SCREENS_SCHEMA | uzhex` will return an empty string.

With the fix then it will return the schema correctly.

### Acceptance criteria

It works.

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [ ] Has the author taken into account the multi-thredded nature of the code?
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.

### Final steps

- [ ] Reviewer has updated the submodule in the main EPICS repo? See **Reviewing work for the subModules of EPICS** in the [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by AdrianPotter** [comment]
This widens the scope slightly, but otherwise it'll never get done. Please could you take a look at the other calls to the commit method in the block server and synoptic parts of the code. All calls should use a similar try-except pattern.

I've had a look at the existing code and I think the exceptions are handled in each case but it's messy. In many cases, commit is called, but it's up to the owner of the caller to catch the exception. For example:

- In config_list_manager, there is an unhandled exception in _import_configs
- That method is called from the constructor to config_list_manager, which also doesn't catch the exception called from the constructor
- It is caught only in the constructor for the BlockServer

This pattern is dangerous because if anyone calls the method from somewhere else, they may not remember to catch the commit exception based on the previously existing pattern, which may be the root cause of this ticket.

The better pattern would be to try-catch-raise. The exception should be caught and handled at each stage, even if the decision is to bubble up the exception to the calling method. Please could you do this for the existing calls to commit.

**Comment by mattclarke** [comment]
Good points - I thought I had written a ticket for this, but apparently not as I cannot find one.

My initial thought was for the VC stuff to fire-and-forget insomuch as it handles its own exceptions and writes them to the log itself rather than escalating them up through the callers. A failure to commit is not critical in the same way that not being able to write to disk is.

Having thought about it a bit more I am not so sure now.

My preference would be for a ticket to review **all** the error handling in the blockserver because, as your examples highlight, it is often inconsistent or non-existent. Perhaps that is too large a ticket though - what do you think?

**Comment by DominicOram** [comment]
Code looks much better. I presume that the commenting out of lines in the bat files was for testing? If so can you revert these.

**Comment by mattclarke** [comment]
Nice catch!

**Pull request merged**
